baseURL = 'https://msankhala.github.io/dcg/'
languageCode = 'en-us'
title = 'Drupal Contribution Guideline (DCG)'
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # logo = 'assets/images/drupal-snippets-logo.png'
